[package]
name = "treasure-chest"
author = "CoW Protocol Developers ğŸ®"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
ethers = "2"
sha2 = "0.10.8"
promkit = "0.2.0"
eyre = "0.6.8"
